# Generated by Django 2.2.15 on 2020-08-24 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_auto_20200824_0539"),
        ("users", "0002_auto_20200824_0521"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="key1",
            field=models.OneToOneField(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_key1",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="key2",
            field=models.OneToOneField(
                blank=True,
                default=2,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_key2",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="key3",
            field=models.ForeignKey(
                blank=True,
                default=3,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_key3",
                to="home.CustomText",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="key4",
            field=models.ForeignKey(
                blank=True,
                default=4,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="user_key4",
                to="home.CustomText",
            ),
        ),
    ]
