# Generated by Django 2.2.15 on 2020-08-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customtext_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='key1',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='customtext_key1', to='home.CustomText'),
        ),
        migrations.AddField(
            model_name='customtext',
            name='key2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='customtext_key2', to='home.CustomText'),
        ),
    ]
