# Generated by Django 2.2.15 on 2020-08-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200825_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='HGytytyt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kjhljhg', models.BigIntegerField()),
            ],
        ),
    ]
